name: zhuishu
description: read book

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^1.0.13
  shared_preferences: ^0.4.3
  cached_network_image: ^0.5.1
  battery: ^0.2.3
  device_info: ^0.4.0
  fluttertoast: ^2.1.1

  annotation_route: ^0.0.2
  build_runner: ^1.3.1
  flutter_easyrefresh: ^1.2.7
  connectivity: ^0.4.3+1
  path_provider: ^0.4.1
  event_bus: ^1.1.0
  screen: ^0.0.5
  # simple_permissions: ^0.1.9
  palette_generator: any

  my_icon:
    path: my_icon/   # 在这里引入第三方icon库

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - images/

